### ISSUE TITLE
Armado de PDF "Base de datos del proyecto, sus diagramas y SQL"

### ISSUE THREAD

**Issue by rociogirardini** [rociogirardini/ispc-tpi-2024#7]
El archivo .sql que contenga las consultas deberá estar acompañado de un documento pdf (sugiero editen en un editor de presentaciones multimedia como presentaciones de google) el cual deberá llamarse “Base de datos del proyecto, sus diagramas y SQL.pdf” y debe tener: 
- en la primer diapositiva debe estar el título del proyecto y los participantes del equipo de trabajo, la fecha, 
- en segunda página debe estar el DER, 
- en tercer página el diagrama Crow Foot y 
- en las páginas siguientes deben estar cada una de las tablas con los datos que tienen cargados. 
-  luego 3 páginas como mínimo, donde detallen el SQL referido a: 
     - Insertar, Actualizar y Eliminar datos. 

Y recién luego de toda esta información cada una de las consultas con sus 3 items: descripción, sintaxis sql y tabla resultante. Es decir, por cada consulta tengan: 
- La descripción de que hace la consulta 
- La consulta SQL correspondiente 
- La tabla resultante (si la tabla es muy grande, dejar una parte y aclarar cuántos son los 
registros que tiene como resultado la consulta) 

Las consultas las deben sobre la Base de datos del proyecto, y deben hacer las siguientes: 
-  Una sola tabla (mostrando todos los datos), 
- Una sola tabla (mostrando algunas columnas), 
- Una sola tabla con where 
- Una sola tabla con where utilizando between 
- Una sola tabla con where utilizando limit 
- Más de 1 tabla con inner join 
-  Más de 1 tabla con inner join y con filtros

**Comment by dorgnachj** [comment]
[Uploading Base de datos del proyecto, sus diagramas y SQL.pdf…]()

**Comment by dorgnachj** [comment]
[Base de datos del proyecto, sus diagramas y SQL.pdf](https://github.com/user-attachments/files/15831908/Base.de.datos.del.proyecto.sus.diagramas.y.SQL.pdf)
